#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               off            # -> buggy

yabai -m config window_shadow                off

yabai -m config window_opacity               off
#yabai -m config window_opacity_duration      0.0           # -> must be commented out. else makes err
yabai -m config active_window_opacity        1.0            # -> meaningless with window_opacity off.
yabai -m config normal_window_opacity        0.90           # -> same.

yabai -m config window_border                off
yabai -m config window_border_width          4.5

yabai -m config active_window_border_color   0xffffffff
yabai -m config normal_window_border_color   0xff000000
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Only tile keyboard-friendly apps
friends_of_keyboard="kitty|Firefox|Notion|Brave Browser|Obisidian"
ugly_when_tiled="KakaoTalk|Slack|System Settings|Notes|App Store|Finder|System Information"
yabai -m rule --add app!="^($friends_of_keyboard)$" manage=off
#yabai -m rule --add app="($ugly_when_tiled)$" manage=off

# Clean up empty spaces with no windows on them.
#yabai -m signal --add event=space_changed action="sh ~/.config/yabai/scripts/cleanEmptySpaces.sh"
#yabai -m signal --add event=space_changed action="sh ~/.config/yabai/scripts/showCurrentSpaceNum.sh > ~/num"

echo "yabai configuration loaded.."

